name: Bug report
description: Create a report to help us improve the Coreflux MQTT Broker!
labels:
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        This repository is for reporting bugs with the Coreflux MQTT Broker, which we respond to on a best-effort basis.
        
        **Please attach the `statuslog` file to your report!** 📄
        To provide us with a detailed context for the issue, attach the `statuslog` file by dragging and dropping it into the issue comment box or by using the GitHub file attachment feature. Ensure any sensitive information is redacted as this file will be publicly accessible.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug 🐞
      description: Please give a clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: To Reproduce 🔄
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior ✅
      description: What is the expected behavior?
      placeholder: |
        E.g. "The broker should accept connections without throwing an error."
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment 🌐
      description: Please select the environment where the bug occurred.
      options:
        - Ubuntu 22.04 LTS (Jammy Jellyfish)
        - Ubuntu 20.04 LTS (Focal Fossa)
        - Debian 12 (Bookworm)
        - Debian 11 (Bullseye)
        - Red Hat Enterprise Linux 9
        - Red Hat Enterprise Linux 8
        - Red Hat Enterprise Linux 7
        - Windows 11
        - Windows 10
        - Windows Server 2022
        - Windows Server 2019
        - Windows Server 2016
        - Raspbian Bullseye
        - Raspbian Buster
        - macOS Monterey
        - macOS Big Sur
        - macOS Catalina
        - Arch Linux 2023.11.01
        - Arch Linux 2023.10.14
        - Arch Linux 2023.09.01
        - Raspberry Pi OS (32-bit, Bookworm)
        - Raspberry Pi OS (64-bit, Bookworm)
        - Raspberry Pi OS (Legacy, 32-bit, Bullseye)
        - Raspberry Pi OS (Legacy, 64-bit, Bullseye)
        - Raspberry Pi Desktop (PC and Mac)
        - Other (Please specify in 'Additional Info')
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Info ➕
      description: Additional info you want to provide such as logs, system info, environment, etc. If you have a `statuslog` file, please attach it to this report.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Service
      description: I agree to follow this project's Code of Conduct
      options:
        - label: I agree
          required: true
